/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ballotSol from "./Ballot.sol";
export { Election__factory } from "./Election__factory";
export { Lock__factory } from "./Lock__factory";
export { VoterRegistry__factory } from "./VoterRegistry__factory";
export { Voting__factory } from "./Voting__factory";
export { VotingSystem__factory } from "./VotingSystem__factory";
