/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./Ballot.sol";
export type { ballotSol };
export type { Election } from "./Election";
export type { Lock } from "./Lock";
export type { VoterRegistry } from "./VoterRegistry";
export type { Voting } from "./Voting";
export type { VotingSystem } from "./VotingSystem";
